### ISSUE TITLE
Dying Unlearns Enchantments

### ISSUE THREAD

**Issue by 69ShadesOfPeanut** [CmdrJane/enchanting-system-overhaul#1]
Required information:
1. Minecraft Version
1.20.1
3. Mod Version
1.0.2
5. Full logs (NOT CRASHREPORT) debug.log or latest.log
[pastebin](https://pastebin.com/FCx2Km2t)
7. Crashreport file(If game crashed)
N/A
9. Description of what you did in order to reproduce bug
Upon dying, all learned enchants are lost

**Comment by CmdrJane** [comment]
fixed
