### ISSUE TITLE
Material-overrides Armor is being ignored

### ISSUE THREAD

**Issue by Xltimus** [CmdrJane/enchanting-system-overhaul#10]
- Minecraft 1.20.1 / Forge 47.3.0
- eso-forge-1.20.1-1.2.1-all

Any changes to the armor.json in the /config/eso/material-overrides does not seem to take effect in-game. All armor pieces seem to refer back to the config.json's default values for maxEnchantments and maxCurses.

**Comment by CmdrJane** [comment]
Fixed in dev
