### ISSUE TITLE
Ability to override default enchantment recipes

### ISSUE THREAD

**Issue by TheRedGeekPlayZ** [CmdrJane/enchanting-system-overhaul#14]
Minecraft Version: 1.20.1
Mod Version: 1.2.2

I wanted to customize the recipe for Fortune, and make it more expensive. But after adding the recipe, the default recipe and the new one I'd created both showed up in the table. I understand this is intended but is it possible to add a way to disable the default recipes?

**Comment by CmdrJane** [comment]
You already can do this, read the wiki
