### ISSUE TITLE
Fabric 1.20.1 Client crash after clicking in enchantment table 

### ISSUE THREAD

**Issue by pewblaze** [CmdrJane/enchanting-system-overhaul#2]
Required information:
1. 1.20.1 Fabric
2. eso-fabric-1.20.1-1.0.5.jar
3. Logs:
https://gist.github.com/pewblaze/fd016fe66bb3761fd5ef38d9d44f2531

4. Crashlog:
https://gist.github.com/pewblaze/cd5215f75d7cd7f27f0665778043d424

6. Joined server, opened enchantment table & clicked inside it -> Crash.

**Comment by CmdrJane** [comment]
Fixed in 1.0.6

**Comment by CmdrJane** [comment]
Fixed in 1.0.6
