### ISSUE TITLE
Mod dosen't honor scrollbar color when using either a texture pack or in-mod retextures

### ISSUE THREAD

**Issue by Shywizz** [CmdrJane/enchanting-system-overhaul#3]
Required information:
1. 1.19.2 (probably applies to any)
2. any
To reproduce: 
Edit `assets/enchanting-system-overhaul/textures/gui/ench_buttons`, more precicely, the third box (pink one)
I expect it to render as the rest, with changed textures
Expectations : 
![reality](https://github.com/CmdrJane/enchanting-system-overhaul/assets/69578335/a6896182-2fd8-43d3-b277-0014392014d7)
Reality : 
![welp](https://github.com/CmdrJane/enchanting-system-overhaul/assets/69578335/45eff4a6-efe9-40d3-ab2d-3f9ce1c3f5e9)

After looking at the code for only a tiny bit, my conclusion is that this seems to be caused by the [EnchantmentListWidget.java](https://github.com/CmdrJane/enchanting-system-overhaul/blob/master/src/main/java/aiefu/eso/client/gui/EnchantmentListWidget.java) file registrering the scrollbar as a `fill` instead of some `blit` magic
Im no expert, but i hope my guess helps.

My hope is to be able to "vanilla-ify" the gui of this really cool mod.
Perhaps in the end proving a resource pack that would achieve that within the mod could be a solution ??
Thank you for reading

**Comment by CmdrJane** [comment]
ah yes fixing that was planned probably in next release

**Comment by CmdrJane** [comment]
Font, scroll menu background and slider colors can now be customized via json files. For examples refer to [this package](https://github.com/CmdrJane/enchanting-system-overhaul/tree/master/src/main/resources/assets/enchanting-system-overhaul/color-settings)
