### ISSUE TITLE
Cannot Apply Enchanted Books To Tools

### ISSUE THREAD

**Issue by Volvith** [CmdrJane/enchanting-system-overhaul#4]
Required information:
Minecraft Version: 1.20.4
Mod Version: v1.1.1

I am unable to add enchanted books to tools on anvils when using this mod.
This happens for any level of any kind of book that is compatible with the tool, and makes books effectively useless past the discovery aspect.
Am i missing a mechanic or something, or is this a bug?

![image](https://github.com/CmdrJane/enchanting-system-overhaul/assets/27238638/e2f22854-4d29-4232-923a-9807c5482b0e)

![image](https://github.com/CmdrJane/enchanting-system-overhaul/assets/27238638/0d78c2ec-adff-4a0b-b124-9514e88bea14)

**Comment by Rebel459** [comment]
This is stated as a mechanic on the mod page

**Comment by CmdrJane** [comment]
This is changed in the most recent version(1.2.0). You can enchant stuff in anvil using books again
