### ISSUE TITLE
Unable to open and use enchanting table

### ISSUE THREAD

**Issue by ittouwjpi** [CmdrJane/enchanting-system-overhaul#5]
Required information:
1. Minecraft Version: 1.20.1 Fabric
2. Mod Version: 1.2.0
3. Description: I am unable to open  and use the enchanting table.  I wonder if its because a bug of the newest version as i can only perform right click but the enchanting UI doens't appear at all.  Honestly i don't know if this is a compatibility issue with other mods or not because i have too many mods. It would really be helpful if you can tell me known incompatibilities. Thanks for reading!!!

**Comment by CmdrJane** [comment]
provide logs fisrt

**Comment by CmdrJane** [comment]
As for incompats anything that changes or touches enchanting table is off the limits. However mods that add enchantments are okay since i do not touch enchantments themselves

**Comment by ittouwjpi** [comment]
[latest.log](https://github.com/CmdrJane/enchanting-system-overhaul/files/15333839/latest.log)
Here is my latest log

**Comment by CmdrJane** [comment]
https://www.curseforge.com/minecraft/mc-mods/easy-magic this is most likely the culprit. Delete it and see if it works then report back

**Comment by ittouwjpi** [comment]
Omg it worked!!! It turns out Easy Magic is incompatible. Thank you for your support <3

**Comment by CmdrJane** [comment]
Easy Magic is obsolete with my mod since it already overhauls enchanting system. Have a good day
