### ISSUE TITLE
Crash when loading gui

### ISSUE THREAD

**Issue by Vikthos** [CmdrJane/enchanting-system-overhaul#8]
1.20.1 (Forge 47.3.0)
eso-forge-1.20.1-1.2.1-all.jar
[crash-2024-06-15_18.07.25-client.txt](https://github.com/user-attachments/files/15848520/crash-2024-06-15_18.07.25-client.txt)
[latest.log](https://github.com/user-attachments/files/15848529/latest.log)

When right clicking the enchanting table my game crashes

**Comment by CmdrJane** [comment]
Fixed
