### ISSUE TITLE
EnchantmentsLeveling preventing upgrading

### ISSUE THREAD

**Issue by Xltimus** [CmdrJane/enchanting-system-overhaul#9]
- Minecraft 1.20.1 / Forge 47.3.0
- eso-forge-1.20.1-1.2.1-all

While having "enableEnchantmentsLeveling": true, when reaching the _max enchantment limit_, the item's enchantments can no longer be upgraded any further. It doesn't matter if in creative mode or if the player actually has learned a higher level.

For an example: enchanting an iron tool with three level 1 enchants will effectively lock the item, unable to go back and upgrade the existing enchants.

This behavior doesn't seem to occur when "enableEnchantmentsLeveling": false

**Comment by CmdrJane** [comment]
Fixed in dev
